services:
    web-frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - /usr/apps/frontend/node_modules
            - .:/usr/apps/frontend/